sudo: false
language: python
python:
  - "2.7"
services:
  - docker
cache:
  pip: true
  directories:
    - $HOME/.ansible/roles/
env:
  matrix:
    - TOXENV=syntax
    - TOXENV=lint

before_install:
  - rm --verbose --recursive --force $HOME/.cache/pip/{http,log}
  - pip install --upgrade pip setuptools

install: pip install tox-travis

script: tox

before_cache:
  - rm --verbose --recursive --force $HOME/.cache/pip/{http,log}
