---
- name: Install systemd service
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
  with_items:
    - "create-snapshot.service"
    - "restore-snapshot.service"
    - "create-snapshot.target"
    - "restore-snapshot.target"
  notify:
    - enable restore-snapshot service
    - enable create-snapshot service

- name: Allow autoextending images
  lineinfile:
    dest: /etc/lvm/lvm.conf
    regexp: '(^\s*)snapshot_autoextend_threshold = 100'
    backrefs: yes
    line: '\1snapshot_autoextend_threshold = 80'
