---
dependency:
  name: galaxy
  options:
    role-file: "requirements.yaml"
lint:
  name: yamllint
  options:
    config-file: ../../.yamllint
platforms:
  - name: deb9
    image: debian:stretch
    groups:
      - vm_hosts
      - vm_hosts__molecule
      - emulated_guests
    privileged: True
provisioner:
  name: ansible
  options:
    # Set verbose if `--debug` passed to molecule
    vvv: "{{ lookup('env', 'MOLECULE_DEBUG') | bool }}"
  config_options:
    defaults:
      roles_path: $HOME/.ansible/roles
  inventory:
    links:
      group_vars: ../../../../../group_vars/
  playbooks:
    prepare: ../default/prepare.yml
    create: ../default/create.yml
    converge: ../default/playbook.yml
    destroy: ../default/destroy.yml
scenario:
  name: qemu
verifier:
  name: testinfra
  directory: ../default/tests
  options:
    v: "${MOLECULE_DEBUG:-false}"
    s: True
  lint:
    name: flake8
    options:
      config: ../../.flake8
