---
dependency:
  name: galaxy
  options:
    role-file: "requirements.yaml"
lint:
  name: yamllint
  options:
    config-file: ../../.yamllint
platforms:
  - name: deb9
    image: debian:stretch
    groups:
      - vm_hosts
      - vm_hosts__molecule
    privileged: True
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: False
  options:
    # Set verbose if `--debug` passed to molecule
    vvv: "{{ lookup('env', 'MOLECULE_DEBUG') | bool }}"
  config_options:
    defaults:
      roles_path: $HOME/.ansible/roles
  inventory:
    links:
      group_vars: ../../../../../group_vars/
scenario:
  name: default
  test_sequence:
    # - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  options:
    v: "${MOLECULE_DEBUG:-false}"
    s: True
  lint:
    name: flake8
    options:
      config: ../../.flake8
