---
dependency:
  name: galaxy
  options:
    role-file: "requirements.yaml"
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: ../../.yamllint
platforms:
  - name: deb9
    image: debian:stretch
    groups:
      - vm_hosts
provisioner:
  name: ansible
  options: {vvv: True}
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
