---

- name: Download PXE images
  get_url:
    url: "{{ centos_mirror }}/7/os/x86_64/images/pxeboot/{{ item }}"
    dest: "{{ vm_image_dir }}/{{ inventory_hostname }}/{{ item }}"
  with_items:
    - initrd.img
    - vmlinuz

- name: Boot the VM using the PXE images
  virt_boot:
    guest: "{{ inventory_hostname }}"
    kernel: "{{ vm_image_dir }}/{{ inventory_hostname }}/vmlinuz"
    initrd: "{{ vm_image_dir }}/{{ inventory_hostname }}/initrd.img"
    cmdline: "inst.text latefcload inst.ks={{ ks_url }} inst.sshd devfs=nomount ip=dhcp"
